// Auto-generated by geo_spec.py
lc = 0.08;

// Rectangle: 3.0 x 2.0 + 1 hole(s)
Point(1) = { -1.5, -1.0, 0, lc};
Point(2) = {  1.5, -1.0, 0, lc};
Point(3) = {  1.5,  1.0, 0, lc};
Point(4) = { -1.5,  1.0, 0, lc};
Line(1) = {1, 2};  // bottom
Line(2) = {2, 3};  // right
Line(3) = {3, 4};  // top
Line(4) = {4, 1};  // left
Curve Loop(1) = {1, 2, 3, 4};
Point(5) = { 1.100000, 0.300000, 0, lc};
Point(6) = { 1.012132, 0.512132, 0, lc};
Point(7) = { 0.800000, 0.600000, 0, lc};
Point(8) = { 0.587868, 0.512132, 0, lc};
Point(9) = { 0.500000, 0.300000, 0, lc};
Point(10) = { 0.587868, 0.087868, 0, lc};
Point(11) = { 0.800000, 0.000000, 0, lc};
Point(12) = { 1.012132, 0.087868, 0, lc};
Point(13) = { 0.800000, 0.300000, 0, lc};
Circle(5) = {5, 13, 6};
Point(14) = { 0.800000, 0.300000, 0, lc};
Circle(6) = {6, 14, 7};
Point(15) = { 0.800000, 0.300000, 0, lc};
Circle(7) = {7, 15, 8};
Point(16) = { 0.800000, 0.300000, 0, lc};
Circle(8) = {8, 16, 9};
Point(17) = { 0.800000, 0.300000, 0, lc};
Circle(9) = {9, 17, 10};
Point(18) = { 0.800000, 0.300000, 0, lc};
Circle(10) = {10, 18, 11};
Point(19) = { 0.800000, 0.300000, 0, lc};
Circle(11) = {11, 19, 12};
Point(20) = { 0.800000, 0.300000, 0, lc};
Circle(12) = {12, 20, 5};
Curve Loop(13) = {5,6,7,8,9,10,11,12};
Plane Surface(1) = {1, 13};

// ---- Boundary Physical Groups ----
Mesh.SaveAll = 1;
Physical Surface("domain", 200) = {1};
Physical Curve("左_固定", 101) = {4};
Physical Curve("右_拉力_1000000.0", 102) = {2};

// ---- FEM Config (auto-read by run.py) ----
// @FEM:fix=左_固定
// @FEM:traction=右_拉力_1000000.0,1000000.0,0

// ---- Output ----
Mesh.SaveGroupsOfNodes = 1;
Mesh.SaveGroupsOfElements = 1;
Mesh 2;