// Auto-generated by geo_spec.py
lc = 0.5;

// Rectangle: 3.0 x 2.0
Point(1) = { -1.5, -1.0, 0, lc};
Point(2) = {  1.5, -1.0, 0, lc};
Point(3) = {  1.5,  1.0, 0, lc};
Point(4) = { -1.5,  1.0, 0, lc};
Line(1) = {1, 2};  // bottom
Line(2) = {2, 3};  // right
Line(3) = {3, 4};  // top
Line(4) = {4, 1};  // left
Curve Loop(1) = {1, 2, 3, 4};
Plane Surface(1) = {1};

// ---- Boundary Physical Groups ----
Mesh.SaveAll = 1;
Physical Surface("domain", 200) = {1};

// ---- FEM Config (auto-read by run.py) ----

// ---- Output ----
Mesh.SaveGroupsOfNodes = 1;
Mesh.SaveGroupsOfElements = 1;
Mesh 2;